from pathlib import Path

queue_path = Path('deduper/family_recertification_queue.py')
text = queue_path.read_text()

old = '''    def _create_current_schema(self) -> None:\n        self.database.connection.executescript(\n            \"\"\"\n            CREATE TABLE IF NOT EXISTS family_recertification_jobs (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                deleted_key TEXT NOT NULL,\n                protected_key TEXT NOT NULL,\n                status TEXT NOT NULL DEFAULT 'pending',\n                attempt_count INTEGER NOT NULL DEFAULT 0,\n                last_error TEXT,\n                last_attempt_at TEXT,\n                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n                completed_at TEXT\n            );\n            CREATE TABLE IF NOT EXISTS family_recertification_members (\n                recertification_id INTEGER NOT NULL\n                    REFERENCES family_recertification_jobs(id) ON DELETE CASCADE,\n                priority INTEGER NOT NULL,\n                asset_key TEXT NOT NULL,\n                PRIMARY KEY (recertification_id, asset_key),\n                UNIQUE (recertification_id, priority)\n            );\n            CREATE INDEX IF NOT EXISTS family_recertification_status_idx\n                ON family_recertification_jobs(status, id);\n            \"\"\"\n        )\n        columns = {\n            str(row[\"name\"])\n            for row in self.database.connection.execute(\n                \"PRAGMA table_info(family_recertification_jobs)\"\n            ).fetchall()\n        }\n        if \"attempt_count\" not in columns:\n            self.database.connection.execute(\n                \"ALTER TABLE family_recertification_jobs \"\n                \"ADD COLUMN attempt_count INTEGER NOT NULL DEFAULT 0\"\n            )\n        if \"last_error\" not in columns:\n            self.database.connection.execute(\n                \"ALTER TABLE family_recertification_jobs ADD COLUMN last_error TEXT\"\n            )\n        if \"last_attempt_at\" not in columns:\n            self.database.connection.execute(\n                \"ALTER TABLE family_recertification_jobs ADD COLUMN last_attempt_at TEXT\"\n            )\n'''

new = '''    def _create_current_schema(self) -> None:\n        # Create only the base tables first. Existing prerelease databases may\n        # already contain a partial version of the modern table, and SQLite's\n        # CREATE TABLE IF NOT EXISTS will not add its missing columns. Indexes\n        # must therefore be created only after every required column exists.\n        self.database.connection.executescript(\n            \"\"\"\n            CREATE TABLE IF NOT EXISTS family_recertification_jobs (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                deleted_key TEXT NOT NULL,\n                protected_key TEXT NOT NULL,\n                status TEXT NOT NULL DEFAULT 'pending',\n                attempt_count INTEGER NOT NULL DEFAULT 0,\n                last_error TEXT,\n                last_attempt_at TEXT,\n                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n                completed_at TEXT\n            );\n            CREATE TABLE IF NOT EXISTS family_recertification_members (\n                recertification_id INTEGER NOT NULL\n                    REFERENCES family_recertification_jobs(id) ON DELETE CASCADE,\n                priority INTEGER NOT NULL,\n                asset_key TEXT NOT NULL,\n                PRIMARY KEY (recertification_id, asset_key),\n                UNIQUE (recertification_id, priority)\n            );\n            \"\"\"\n        )\n        columns = {\n            str(row[\"name\"])\n            for row in self.database.connection.execute(\n                \"PRAGMA table_info(family_recertification_jobs)\"\n            ).fetchall()\n        }\n        additions = (\n            (\"status\", \"TEXT NOT NULL DEFAULT 'pending'\"),\n            (\"attempt_count\", \"INTEGER NOT NULL DEFAULT 0\"),\n            (\"last_error\", \"TEXT\"),\n            (\"last_attempt_at\", \"TEXT\"),\n            (\"created_at\", \"TEXT\"),\n            (\"completed_at\", \"TEXT\"),\n        )\n        for name, declaration in additions:\n            if name not in columns:\n                self.database.connection.execute(\n                    f\"ALTER TABLE family_recertification_jobs ADD COLUMN {name} {declaration}\"\n                )\n\n        self.database.connection.execute(\n            \"\"\"\n            CREATE INDEX IF NOT EXISTS family_recertification_status_idx\n            ON family_recertification_jobs(status, id)\n            \"\"\"\n        )\n'''

if old not in text:
    raise SystemExit('schema creation anchor missing')
queue_path.write_text(text.replace(old, new, 1))

test_path = Path('tests/test_family_recertification_schema_migration.py')
test = test_path.read_text()
insert = '''\n    def test_partial_modern_table_missing_status_is_repaired_before_indexing(self) -> None:\n        with tempfile.TemporaryDirectory() as directory:\n            db = CertifiedDatabase(Path(directory) / \"deduper.sqlite3\")\n            with db.connection:\n                db.connection.executescript(\"\"\"\n                    CREATE TABLE family_recertification_jobs (\n                        id INTEGER PRIMARY KEY AUTOINCREMENT,\n                        deleted_key TEXT NOT NULL,\n                        protected_key TEXT NOT NULL\n                    );\n                    CREATE TABLE family_recertification_members (\n                        recertification_id INTEGER NOT NULL,\n                        priority INTEGER NOT NULL,\n                        asset_key TEXT NOT NULL,\n                        PRIMARY KEY (recertification_id, asset_key),\n                        UNIQUE (recertification_id, priority)\n                    );\n                    INSERT INTO family_recertification_jobs\n                        (id, deleted_key, protected_key)\n                    VALUES (9, 'gone-early.jpg', 'keep-early.jpg');\n                    INSERT INTO family_recertification_members\n                        (recertification_id, priority, asset_key)\n                    VALUES (9, 0, 'keep-early.jpg');\n                \"\"\")\n            queue = FamilyRecertificationQueue(db)\n            pending = queue.pending()\n            self.assertEqual(len(pending), 1)\n            self.assertEqual(pending[0].recertification_id, 9)\n            self.assertEqual(pending[0].status, 'pending')\n            columns = {row['name'] for row in db.connection.execute(\n                \"PRAGMA table_info(family_recertification_jobs)\"\n            )}\n            self.assertIn('status', columns)\n            indexes = {row['name'] for row in db.connection.execute(\n                \"PRAGMA index_list(family_recertification_jobs)\"\n            )}\n            self.assertIn('family_recertification_status_idx', indexes)\n            db.close()\n'''
anchor = '\n\nif __name__ == \'__main__\':\n'
if anchor not in test:
    raise SystemExit('test insertion anchor missing')
test_path.write_text(test.replace(anchor, insert + anchor, 1))
